---
title: "Data from API"
output: html
---


```{r}
library(tidyverse)
library(utils)
library(mapdata)
library(maptools)
library(gganimate)
```

```{r}
fullDf <- read.delim('../RawDataSets/ebd_sancra_smp_relApr-2024.txt')
```


```{r}
fullDf %>% head()
```

```{r}

df <- fullDf %>% 
  select(LATITUDE, LONGITUDE, date = OBSERVATION.DATE,start = TIME.OBSERVATIONS.STARTED) %>%
  separate(col = date, sep= '-', into = c("Year", "Month", "Day"), convert = TRUE) %>% filter(!is.na(Year)) %>%
  mutate(YearMo = as.integer((Year - 2012) * 12 + Month))

head(df)
```
```{r}
mday <- function(Month, Day) {
  order = c(0,31,28,31,30,31,30,31,31,30,31,30,31,30,31)
  ans = Day
  for (i in 1:Month) {
    ans = ans + order[i]
  }
  return (ans)
}

```

```{r, fig.height = 10, fig.width = 10}
usa =  map_data("usa")
bin = df %>%
  filter(LONGITUDE >= -140 & Year == 2022) %>%
  mutate(mday = map2_int(Month, Day, mday)) %>%
  ggplot() + 
  geom_polygon(data = usa, mapping = aes(x = long, y = lat, group = group), color= 'black', fill = 'white') +
  geom_hex(mapping = aes(x = LONGITUDE, y = LATITUDE), bins = 100) + 
  transition_time(mday) + 
  labs(y = "Latitude", x = "Longitude", title = "SandHill Crane Spottings each day in the US; Currently showing: {floor(frame_time)}") + 
  scale_fill_gradientn(colours = c( "#4d0803", "#ed2f21", "green", 'green'), values = c(0,0.1,0.1 + 1/500, 1), limits = c(0,500)) + 
  theme_minimal()
bin
```

```{r}
anim_save("SanCrasOverTime.gif", animation = bin)
```